name: CI

on:
  push:
    branches:
      - main
      - 'release/*'

  pull_request:
    branches:
      - main
    path-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@main
    - name: Starting with GitHub Actions
      run: echo 'Hello, world!'
    - name: Just beginning
      run: |
        echo 'Please, work!'
        exit 0
